## YAML Template.
server:
    servlet:
        context-path: /carmanager
        port: 8080
        uri-encoding: utf8

spring:
    # jdbc_config   datasource
    datasource:
        url: jdbc:sqlserver://169.254.192.87:1433;DatabaseName=wjdb
        username: sa
        password: Emswjdb2018
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        # Hikari will use the above plus the following to setup connection pooling
        type: com.zaxxer.hikari.HikariDataSource
        minimum-idle: 5
        maximum-pool-size: 500
        auto-commit: true
        idle-timeout: 30000
        hikari.pool-name: DatebookHikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
    #jpa config
    jpa:
        hibernate:
            #可选参数 
            #create 启动时删数据库中的表，然后创建，退出时不删除数据表 
            #create-drop 启动时删数据库中的表，然后创建，退出时删除数据表 如果表不存在报错 
            #update 如果启动时表格式不一致则更新表，原有数据保留 
            #validate 项目启动表结构进行校验 如果不一致则报错
            #none 则不进行任何操作
            ddl-auto: none        
        show-sql: false
    #让控制器输出的json格式更美观
    jackson:
        serialization:
            indent-output: true
        
